# Generated by Django 4.2.5 on 2023-10-05 08:41

import django.db.models.deletion
import timescale.db.models.fields
from django.db import migrations, models

import dashboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.SlugField(default=dashboard.models.browser_instance, max_length=64, verbose_name='Instance ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Browser',
                'verbose_name_plural': 'Browsers',
                'db_table': 'browser',
            },
        ),
        migrations.CreateModel(
            name='PointerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('interval', models.IntegerField(verbose_name='Interval (ms)')),
                ('avg_velocity', models.FloatField(verbose_name='Average Velocity')),
                ('traversed_distance', models.FloatField(verbose_name='Traversed Distance')),
                ('start_x', models.IntegerField(verbose_name='Start X')),
                ('start_y', models.IntegerField(verbose_name='Start X')),
                ('end_x', models.IntegerField(verbose_name='End X')),
                ('end_y', models.IntegerField(verbose_name='End X')),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.browser')),
            ],
            options={
                'verbose_name': 'Pointer Status',
                'verbose_name_plural': 'Pointer Statuses',
                'db_table': 'pointer_status',
            },
        ),
    ]
